# Generated by Django 5.2.7 on 2025-10-14 16:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('store_in', models.PositiveIntegerField(default=0)),
                ('store_out', models.PositiveIntegerField(default=0)),
                ('remaining_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BarStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('open_stock', models.PositiveIntegerField(default=0)),
                ('added_stock', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('closing_stock', models.PositiveIntegerField(default=0, editable=False)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_stocks', to='inventory.storeitem')),
            ],
        ),
    ]
